plugins {
    id 'com.android.application'
}

android {
    namespace 'uz.arena.futbol'
    compileSdk 34

    defaultConfig {
        applicationId "uz.arena.futbol"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
        debug {
            debuggable false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

// Tashqi kutubxonalarsiz — faqat WebView
dependencies {
}
